# Generated by Django 3.0 on 2022-03-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='schedule_management',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='日程id')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='日程标题')),
                ('content', models.CharField(max_length=1000, verbose_name='日程内容')),
                ('date', models.DateField(auto_now=True, verbose_name='日程内容')),
                ('is_delete', models.IntegerField(default=1, verbose_name='用户状态，0为删除，1为正常')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='用户id')),
                ('login_name', models.CharField(db_index=True, max_length=50, verbose_name='登录名')),
                ('password', models.CharField(max_length=6, verbose_name='密码')),
                ('nickname', models.CharField(max_length=30, verbose_name='昵称')),
                ('role', models.IntegerField(default=2, verbose_name='用户角色，0是为超级管理，1位普通管理员，2位用户')),
                ('status', models.IntegerField(default=1, verbose_name='用户状态，0为停用，1为启用')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
    ]
